
export async function GET() {
    return Response.json({
        "result": {
            "battery_data": [
                {
                    "make": "simulator",
                    "model": "simulator range",
                    "model_variant": "simulator variant",
                    "year": "2020",
                    "mileage": "6421",
                    "battery_capacity_nominal_kwh": "54.7",
                    "battery_capacity_usable_kwh": "52.0",
                    "battery_warranty_months": "96",
                    "battery_warranty_miles": "100000",
                    "battery_remaining_warranty_months": "59",
                    "battery_remaining_warranty_miles": "93579",
                    "real_combined_max_range_miles": "220",
                    "wltp_range_miles": "239",
                    "real_battery_efficiency_mi_per_kwh": "4.24",
                    "image_url": "https://ev-database.org/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01@2x.jpg"
                },
                {
                    "make": "simulator",
                    "model": "simulator range",
                    "model_variant": "simulator variant",
                    "year": "2020",
                    "mileage": "6421",
                    "battery_capacity_nominal_kwh": "54.7",
                    "battery_capacity_usable_kwh": "52.0",
                    "battery_warranty_months": "96",
                    "battery_warranty_miles": "100000",
                    "battery_remaining_warranty_months": "59",
                    "battery_remaining_warranty_miles": "93579",
                    "real_combined_max_range_miles": "220",
                    "wltp_range_miles": "239",
                    "real_battery_efficiency_mi_per_kwh": "4.24",
                    "image_url": "https://ev-database.org/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01@2x.jpg"
                },
                {
                    "make": "simulator",
                    "model": "simulator range",
                    "model_variant": "simulator variant",
                    "year": "2020",
                    "mileage": "6421",
                    "battery_capacity_nominal_kwh": "54.7",
                    "battery_capacity_usable_kwh": "52.0",
                    "battery_warranty_months": "96",
                    "battery_warranty_miles": "100000",
                    "battery_remaining_warranty_months": "59",
                    "battery_remaining_warranty_miles": "93579",
                    "real_combined_max_range_miles": "220",
                    "wltp_range_miles": "239",
                    "real_battery_efficiency_mi_per_kwh": "4.24",
                    "image_url": "https://ev-database.org/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01@2x.jpg"
                },
                {
                    "make": "simulator",
                    "model": "simulator range",
                    "model_variant": "simulator variant",
                    "year": "2020",
                    "mileage": "6421",
                    "battery_capacity_nominal_kwh": "54.7",
                    "battery_capacity_usable_kwh": "52.0",
                    "battery_warranty_months": "96",
                    "battery_warranty_miles": "100000",
                    "battery_remaining_warranty_months": "59",
                    "battery_remaining_warranty_miles": "93579",
                    "real_combined_max_range_miles": "220",
                    "wltp_range_miles": "239",
                    "real_battery_efficiency_mi_per_kwh": "4.24",
                    "image_url": "https://ev-database.org/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01@2x.jpg"
                },
                {
                    "make": "simulator",
                    "model": "simulator range",
                    "model_variant": "simulator variant",
                    "year": "2020",
                    "mileage": "6421",
                    "battery_capacity_nominal_kwh": "54.7",
                    "battery_capacity_usable_kwh": "52.0",
                    "battery_warranty_months": "96",
                    "battery_warranty_miles": "100000",
                    "battery_remaining_warranty_months": "59",
                    "battery_remaining_warranty_miles": "93579",
                    "real_combined_max_range_miles": "220",
                    "wltp_range_miles": "239",
                    "real_battery_efficiency_mi_per_kwh": "4.24",
                    "image_url": "https://ev-database.org/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01@2x.jpg"
                },
                {
                    "make": "simulator",
                    "model": "simulator range",
                    "model_variant": "simulator variant",
                    "year": "2020",
                    "mileage": "6421",
                    "battery_capacity_nominal_kwh": "54.7",
                    "battery_capacity_usable_kwh": "52.0",
                    "battery_warranty_months": "96",
                    "battery_warranty_miles": "100000",
                    "battery_remaining_warranty_months": "59",
                    "battery_remaining_warranty_miles": "93579",
                    "real_combined_max_range_miles": "220",
                    "wltp_range_miles": "239",
                    "real_battery_efficiency_mi_per_kwh": "4.24",
                    "image_url": "https://ev-database.org/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01@2x.jpg"
                },
                {
                    "make": "simulator",
                    "model": "simulator range",
                    "model_variant": "simulator variant",
                    "year": "2020",
                    "mileage": "6421",
                    "battery_capacity_nominal_kwh": "54.7",
                    "battery_capacity_usable_kwh": "52.0",
                    "battery_warranty_months": "96",
                    "battery_warranty_miles": "100000",
                    "battery_remaining_warranty_months": "59",
                    "battery_remaining_warranty_miles": "93579",
                    "real_combined_max_range_miles": "220",
                    "wltp_range_miles": "239",
                    "real_battery_efficiency_mi_per_kwh": "4.24",
                    "image_url": "https://ev-database.org/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01@2x.jpg"
                },
                {
                    "make": "simulator",
                    "model": "simulator range",
                    "model_variant": "simulator variant",
                    "year": "2020",
                    "mileage": "6421",
                    "battery_capacity_nominal_kwh": "54.7",
                    "battery_capacity_usable_kwh": "52.0",
                    "battery_warranty_months": "96",
                    "battery_warranty_miles": "100000",
                    "battery_remaining_warranty_months": "59",
                    "battery_remaining_warranty_miles": "93579",
                    "real_combined_max_range_miles": "220",
                    "wltp_range_miles": "239",
                    "real_battery_efficiency_mi_per_kwh": "4.24",
                    "image_url": "https://ev-database.org/img/auto/Renault_Zoe_2020/Renault_Zoe_2020-01@2x.jpg"
                }
            ]
        }
    })
}