import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css"
import "../theme/globals.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EV Battry Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={inter.className}>{<Theme>
        {children}
      </Theme>}
        <script defer src="https://app.kastro.chat/script/widget/224:24a738fe87cf6b2858cd2638ff49cf22"></script>
      </body>

    </html>
  );
}
